# Generated by Django 6.0.1 on 2026-01-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='opt',
            new_name='otp',
        ),
    ]
