# Generated by Django 6.0.1 on 2026-02-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockin_total_price_stockin_unit_price_stockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
