# Generated by Django 6.0.1 on 2026-03-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
    ]
