# Generated by Django 6.0.1 on 2026-03-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stockin_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockout',
            old_name='create_by',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='stockout',
            old_name='update_by',
            new_name='update_at',
        ),
        migrations.AlterField(
            model_name='stockout',
            name='reason',
            field=models.CharField(choices=[('SALE', 'sale'), ('DAMAGE', 'damage'), ('EXPIRED', 'expired'), ('TRANSFER', 'transfer'), ('OTHER', 'other')], default='sale', max_length=15),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
    ]
