# Generated by Django 6.0.1 on 2026-03-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockout',
            name='reason',
            field=models.CharField(choices=[('SALE', 'sale'), ('DAMAGE', 'damage'), ('EXPIRED', 'expired'), ('TRANSFER', 'transfer'), ('OTHER', 'other')], default='SALE', max_length=15),
        ),
    ]
